"""What people read: charts, the findings readout, OKRs and the README summary.

Every number is read from the build's results. None is typed in by hand, so the prose
cannot drift from the data.
"""
from __future__ import annotations

import math
import pathlib

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

BLUE, GREY, RED = "#1f5f8b", "#9aa5b1", "#c0392b"
FAKE = ("> **Generated test data: these are not findings.** This output proves the pipeline end to end. "
        "Run the build on the real export to produce the real readout.")


def _nan(v) -> bool:
    return v is None or (isinstance(v, float) and math.isnan(v))


def pct(v, d=1):
    return "n/a" if _nan(v) else f"{100 * v:.{d}f}%"


def pp(v):
    return "n/a" if _nan(v) else f"{100 * v:+.2f} pp"


def money(v):
    return "n/a" if _nan(v) else f"${v:,.2f}"


def figures(funnel_df, daily, checkout_df, out: pathlib.Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    f = funnel_df[funnel_df["breakdown"] == "overall"].sort_values("step_order")
    fig, ax = plt.subplots(figsize=(8.5, 4.2))
    steps, n, r = list(f["step"])[::-1], list(f["sessions"])[::-1], list(f["rate_from_previous"])[::-1]
    ax.barh(steps, n, color=BLUE)
    for y, (v, rate) in enumerate(zip(n, r)):
        ax.text(v, y, f"  {v:,}  ({pct(rate)} of previous step)", va="center", fontsize=8)
    ax.set_xlim(0, max(n) * 1.55)
    ax.set_xlabel("Sessions")
    ax.set_title("Where shoppers drop out: nested funnel, all sessions", loc="left")
    fig.tight_layout()
    fig.savefig(out / "funnel.png", dpi=150)
    plt.close(fig)

    d = daily.sort_values("date")
    fig, ax = plt.subplots(figsize=(9, 3.8))
    ax.plot(d["date"], 100 * d["conversion"], color=GREY, lw=1, label="Daily")
    ax.plot(d["date"], 100 * d["conversion"].rolling(7, min_periods=4).mean(), color=BLUE, lw=2, label="7-day average")
    # Labels sit in a staggered strip above the plot, so dates a day apart never collide with each other or the data.
    for i, (_, row) in enumerate(d[d["calendar_label"].notna()].iterrows()):
        ax.axvline(row["date"], color=RED, ls="--", lw=0.8)
        ax.annotate(row["calendar_label"], xy=(row["date"], 1.0), xycoords=("data", "axes fraction"),
                    xytext=(0, 3 + 10 * (i % 3)), textcoords="offset points", ha="center", fontsize=7,
                    color=RED, annotation_clip=False)
    ax.set_ylabel("Session conversion (%)")
    ax.set_title("Conversion through peak trading", loc="left", pad=38)
    ax.legend(loc="upper left", fontsize=8, frameon=False)
    fig.autofmt_xdate()
    fig.tight_layout()
    fig.savefig(out / "daily_conversion.png", dpi=150)
    plt.close(fig)

    c = checkout_df.set_index("device_category")
    cols = [("added_delivery_rate", "Added delivery"), ("added_payment_rate", "Added payment"), ("purchased_rate", "Purchased")]
    fig, ax = plt.subplots(figsize=(8, 3.8))
    width = 0.8 / max(len(c), 1)
    for j, (dev, row) in enumerate(c.iterrows()):
        xs = [i + j * width for i in range(len(cols))]
        ax.bar(xs, [100 * row[k] for k, _ in cols], width=width, label=f"{dev} ({int(row['began_checkout']):,} checkouts)")
    ax.set_xticks([i + width * (len(c) - 1) / 2 for i in range(len(cols))], [label for _, label in cols])
    ax.set_ylabel("% of sessions that began checkout")
    ax.set_title("Finishing the shop, by device", loc="left")
    ax.legend(fontsize=8, frameon=False)
    fig.tight_layout()
    fig.savefig(out / "checkout_by_device.png", dpi=150)
    plt.close(fig)


def findings_markdown(r: dict, real: bool) -> str:
    o, s, f, c, bd = r["overview"], r["search"], r["follow_up"], r["checkout"], r["biggest_drop"]
    checks = r["audit"]
    L = ["# Findings", ""]
    if not real:
        L += [FAKE, ""]
    L += [f"_Generated by `python -m basketpath.build` from {r['source']}. Every number is read from `marts/`; "
          "none is typed by hand._", "", "## The data, and whether it can be trusted", "",
          f"{o['sessions']:,} sessions from {o['users']:,} users between {o['first_day']} and {o['last_day']} "
          f"({o['events']:,} events). {o['purchasing_sessions']:,} sessions included a purchase: session conversion "
          f"of {pct(o['conversion'], 2)} (95% CI {pct(o['conversion_lo'], 2)} to {pct(o['conversion_hi'], 2)}).", ""]
    fails = sorted([x for x in checks if x["status"] == "fail"], key=lambda x: {"high": 0, "medium": 1}.get(x["severity"], 2))
    L.append(f"The tracking audit ran {len(checks)} checks before any analysis, and {len(fails)} failed"
             + (". In order of severity:" if fails else "."))
    for x in fails:
        L.append(f"- **{x['check'].replace('_', ' ')}** ({x['severity']}, owner: {x['owner']}): "
                 f"{x['numerator']:,} of {x['denominator']:,} ({pct(x['rate'], 3)}), above the limit of {pct(x['threshold'], 1)}.")
    for x in [x for x in checks if x["status"] == "info"]:
        L.append(f"- For information: {x['numerator']:,} of {x['denominator']:,} search terms ({pct(x['rate'])}) "
                 "are placeholders written by Google's obfuscation, not tracking faults.")
    L += ["", "Scorecard: `marts/audit_scorecard.csv`. Field coverage against the tracking plan: `marts/tracking_coverage.csv`.", "",
          "## Where shoppers drop out", "",
          f"The largest proportional loss is from **{bd['from_step'].lower()}** to **{bd['to_step'].lower()}**: "
          f"{pct(bd['kept'])} of the {bd['sessions_before']:,} sessions at the first step reached the second.", "",
          "| Step | Sessions | Share of all sessions | Share of previous step |", "|---|---:|---:|---:|"]
    for st in r["funnel_overall"]:
        L.append(f"| {st['step']} | {st['sessions']:,} | {pct(st['rate_from_start'], 2)} | {pct(st['rate_from_previous'])} |")
    L += ["", "![Funnel](figures/funnel.png)", "",
          "Steps are nested: a session counts at a step only if it reached every earlier step. "
          "Breakdowns by device, visitor type and channel are in `marts/funnel.csv`.", "",
          "## Search: does it help, or do people who search already intend to buy?", ""]
    if not s["enough"]:
        L.append(f"Only {s['search_sessions']:,} sessions used site search, too few to answer this.")
    else:
        n, ad = s["naive"], s["adjusted"]
        L += [f"{pct(s['search_share'])} of sessions used site search. They converted at {pct(n['p1'], 2)} against "
              f"{pct(n['p0'], 2)} for other sessions: a naive difference of {pp(n['diff'])} "
              f"(95% CI {pp(n['lo'])} to {pp(n['hi'])}).", "",
              "But searchers differ before they search. Compared like with like, within groups sharing the same device, "
              "new or returning status, channel and purchase history, the difference is "
              f"{pp(ad['diff'])} (95% CI {pp(ad['lo'])} to {pp(ad['hi'])}), covering {pct(ad['coverage'])} of search sessions."
              + ("" if _nan(s["share_explained"]) else
                 f" The difference in who searches accounts for about {pct(s['share_explained'], 0)} of the naive gap."), ""]
        if ad["lo"] <= 0 <= ad["hi"]:
            L.append("What remains is not distinguishable from zero, so this data cannot show that search itself raises conversion.")
        elif ad["diff"] > 0:
            L.append("A difference remains, but it may still reflect intent these groups do not capture, such as what the "
                     "shopper came for. Observational data cannot separate the two; an experiment can.")
        else:
            L.append("Held like for like, searchers convert less than comparable shoppers who did not search. That is worth "
                     "investigating: it can mean search is failing the people who use it.")
        L += ["", f"Searching sessions reached a product page {pct(s['product_view_rate_search'])} of the time, against "
                  f"{pct(s['product_view_rate_other'])} for other sessions."]
    L += ["", "### The experiment that would settle it", ""]
    if f.get("enough"):
        L += [f"Randomise **users**, not sessions, who search, between current search and a changed version, and measure whether "
              f"each buys within the week. In the baseline weeks {f['weekly_searching_users']:,.0f} users searched each week, "
              f"and {pct(f['baseline_weekly_conversion'], 2)} of them bought.", "",
              "| Smallest relative lift worth detecting | Users per arm | Weeks of search traffic |", "|---:|---:|---:|"]
        L += [f"| {pct(p['relative_lift'], 0)} | {p['users_per_arm']:,} | {p['weeks']} |" for p in f["plans"]]
        L += ["", "Two-sided test at 5% with 80% power. Guardrails: revenue per user and checkout completion. "
              "Agree the smallest lift worth shipping before starting, and do not stop early on a promising result."]
    else:
        L.append("The baseline weeks hold too little search traffic to size a test.")
    L += ["", "## Finishing the shop: checkout by device", ""]
    if c:
        L.append(f"Of sessions that began checkout, {pct(c['mobile'])} completed on mobile against {pct(c['desktop'])} on desktop "
                 f"({c['mobile_n']:,} and {c['desktop_n']:,} checkouts): a difference of {pp(c['diff'])} "
                 f"(95% CI {pp(c['lo'])} to {pp(c['hi'])}; {'significant at 5%' if c['p_value'] < 0.05 else 'within noise'}).")
    L += ["", "![Checkout by device](figures/checkout_by_device.png)", "", "## Peak trading", "",
          "| Window | Days | Sessions a day | Conversion | Change vs baseline | Checkout completion | Revenue per purchasing session |",
          "|---|---:|---:|---:|---:|---:|---:|"]
    for w in r["windows"]:
        change = "baseline" if w["role"] == "baseline" else \
            f"{pp(w['conversion_change_pp'])} ({'p < 0.05' if w['conversion_p_value'] < 0.05 else 'within noise'})"
        L.append(f"| {w['window']} | {w['days']} | {w['sessions_per_day']:,.0f} | {pct(w['conversion'], 2)} | {change} | "
                 f"{pct(w['checkout_completion'])} | {money(w['revenue_per_purchasing_session'])} |")
    L += ["", "![Conversion through peak trading](figures/daily_conversion.png)", "",
          "## Custom segments", "", "| Segment | Sessions | Share of sessions | Conversion | Revenue per session |",
          "|---|---:|---:|---:|---:|"]
    for g in r["segments"]:
        L.append(f"| {g['segment']} | {g['sessions']:,} | {pct(g['share_of_sessions'])} | {pct(g['conversion'], 2)} | {money(g['revenue_per_session'])} |")
    L += ["", "Each segment is a SQL rule on the session table, listed in `marts/segments.csv`, so it can be rebuilt in any analytics tool.",
          "", "## What this data cannot tell us", "",
          "- It is Google's obfuscated sample from its own merchandise store, not a grocer's site. Some values are placeholders.",
          "- Everything here is observational: differences between groups describe who did what, not what caused it.",
          "- Visits are identified by `ga_session_id`. Events without one cannot be placed in a visit (see the audit).",
          "- Revenue is as tracked. Where transaction IDs are missing, orders cannot be de-duplicated.", ""]
    return "\n".join(L)


def okrs_markdown(r: dict, real: bool) -> str:
    s, c, o = r["search"], r["checkout"], r["overview"]
    steps = {st["step"]: st for st in r["funnel_overall"]}
    basket = steps["Added to basket"]["rate_from_previous"]
    txn = next(x for x in r["audit"] if x["check"] == "purchases_missing_transaction_id")
    valid = 1 - txn["rate"] if not _nan(txn["rate"]) else float("nan")
    up = lambda v: "n/a" if _nan(v) else pct(min(v * 1.1, 0.99))
    L = ["# OKRs for a search, browse and checkout product team", ""]
    if not real:
        L += [FAKE, ""]
    L += ["_Generated by `python -m basketpath.build` from measured baselines. Targets are proposals to agree with the "
          "product team, not commitments. Metric definitions: [metrics.md](metrics.md)._", "",
          "## Objective 1: Help shoppers find the right product quickly", "",
          f"- **KR1** Raise the share of search sessions that reach a product page from {pct(s['product_view_rate_search'])} "
          f"to {up(s['product_view_rate_search'])} (10% relative).",
          f"- **KR2** Raise the share of product-viewing sessions that add to basket from {pct(basket)} to {up(basket)} (10% relative).",
          "", "## Objective 2: Make finishing the shop effortless on every device", ""]
    if c and c["desktop"] > c["mobile"]:
        L.append(f"- **KR3** Raise mobile checkout completion from {pct(c['mobile'])} to "
                 f"{pct(c['mobile'] + (c['desktop'] - c['mobile']) / 2)}, closing half the gap to desktop ({pct(c['desktop'])}).")
    elif c:
        L.append(f"- **KR3** Hold mobile checkout completion at or above {pct(c['mobile'])} (desktop: {pct(c['desktop'])}).")
    L += [f"- **KR4** Keep purchases with a valid transaction ID at or above 99.5% (currently {pct(valid, 2)}).", "",
          "## Health metrics: must not get worse while the KRs move", "",
          f"- Session conversion: {pct(o['conversion'], 2)}",
          f"- Engaged-session share: {pct(o['engaged_share'])}",
          "- High-severity tracking-audit failures: zero", ""]
    return "\n".join(L)


def readme_block(r: dict) -> str:
    o, s, c, bd = r["overview"], r["search"], r["checkout"], r["biggest_drop"]
    fails = [x["check"].replace("_", " ") for x in r["audit"] if x["status"] == "fail"]
    L = [f"- **Data:** {o['sessions']:,} sessions from {o['users']:,} users, {o['first_day']} to {o['last_day']}. "
         f"Session conversion {pct(o['conversion'], 2)} (95% CI {pct(o['conversion_lo'], 2)} to {pct(o['conversion_hi'], 2)}).",
         f"- **Tracking audit:** {len(fails)} of {len(r['audit'])} checks failed" + (f": {', '.join(fails)}." if fails else "."),
         f"- **Biggest drop:** {bd['from_step'].lower()} to {bd['to_step'].lower()}, where {pct(bd['kept'])} continue."]
    if s["enough"]:
        L.append(f"- **Search:** used in {pct(s['search_share'])} of sessions. Naive conversion gap {pp(s['naive']['diff'])}; "
                 f"like for like {pp(s['adjusted']['diff'])} (95% CI {pp(s['adjusted']['lo'])} to {pp(s['adjusted']['hi'])}).")
    if c:
        L.append(f"- **Checkout completion:** mobile {pct(c['mobile'])}, desktop {pct(c['desktop'])} ({pp(c['diff'])}).")
    return "\n".join(L)
